apiVersion: apps/v1 # Kubernetes API version
kind: Deployment  # Kubernetes resource kind we are creating
metadata:
  name: crm-deployment # name of the deployment
spec:
  selector:
    matchLabels:
      app: crm
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: crm
    spec:
      containers:
      - name: crm
        image: nizarnasraoui/crm-api:1.0 # Image that will be used to containers in the cluster
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_HOST
            value: mysql
          - name: MYSQL_PORT
            value: '3306'
          - name: MYSQL_USER
            value: 'root'
          - name: MYSQL_PASSWORD
            value: 'root'

        ports:
        - containerPort: 8080 # The port that the container is running on in the cluster